server:
  port: 8081
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

#debug: true
#logging:
#  file:
#    name: /tmp/k3p/log/config.log
