server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
spring:
  datasource:
    url: jdbc:postgresql://172.18.0.35:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp: 
        use_metadata_defaults: false
  artemis:
    user: artemis
    password: simetraehcapa
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: secretkey
hu:
  lacztam:
    token:
      keypaths:
        public: /tmp/k3p/public.pem
k3p:
  jwtTokenProperties:
    expireMinute: 600
    issuer: KeePassPlusPlus
    auth: auth
    algorithmSpecification: HMAC512
    algorithmSpecificationArgument: mysecret

#logging:
#  file:
#    name: /opt/apache-tomcat-9.0.73/logs/crypto.log