server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user(?<segment>/?.*), /api$\{segment}
      - id: frontend-service
        uri: lb://frontend-service
        predicates:
        - Path=/frontend/**
        filters: 
        - RewritePath=/frontend(?<segment>/?.*), /api$\{segment}
      - id: keepass-service
        uri: lb://keepass-service
        predicates:
        - Path=/keepass/**
        filters: 
        - RewritePath=/keepass(?<segment>/?.*), /api$\{segment}
hu:
  lacztam:
    token:
      keypaths:
        public: /home/tamas/work/K3P/certs/public.pem

#logging:
#  file:
#    name: /tmp/k3p/log/gateway.log