server:
  port: 8083
#  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
#      defaultZone: http://localhost:9999/discovery
#      defaultZone: http://172.18.0.42:8082/eureka

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.33:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp: 
        use_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: laczoth@gmail.com
    password: qswzirywzdboqzfs
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  artemis:
    user: artemis
    password: simetraehcapa
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: secretkey
hu:
  lacztam:
    token:
      keypaths:
        private: /tmp/k3p/private.pem
        public: /tmp/k3p/public.pem
k3p:
  jwtTokenProperties:
    expireMinute: 600
    issuer: KeePassPlusPlus
    auth: auth
    algorithmSpecification: HMAC512
#    algorithmSpecificationArgument: mysecret
#logging:
#  file:
#    name: /tmp/k3p/log/user.log
