server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
logging:
  file:
    name: /tmp/k3p/log/discovery.log

spring:
  config:
    import: optional:configserver:http://localhost:9999/config
  application:
    name: discovery