server:
  port: '8085'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  config:
    import: optional:configserver:http://localhost:9999/config
  application:
    name: crypto-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      temp:
        use_metadata_defaults: 'false'
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    open-in-view: 'false'
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://172.18.0.35:5432/crypto
  artemis:
    password: simetraehcapa
    user: artemis
k3p:
  jwtTokenProperties:
    issuer: KeePassPlusPlus
    expireMinute: '600'
    auth: auth
    algorithmSpecification: HMAC512
    algorithmSpecificationArgument: mysecret
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: secretkey
hu:
  lacztam:
    token:
      keypaths:
        public: /tmp/k3p/public.pem
logging:
  file:
    name: /tmp/k3p/logs/crypto.log
