server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka

redis:
  password: 1hAe8EDX6gBG0pC8daeW
  database: 0
spring:
  data:
#    mongodb:
#      uri: mongodb://mongo:m@localhost:27017/mydatabase?authSource=admin
#      authentication-database: admin
  config:
    import: optional:configserver:http://localhost:9999/config
  application:
    name: keepass
  redis:
    host: 172.18.0.36
    port: 6379
  datasource:
    url: jdbc:postgresql://172.18.0.34:5432/keepass
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp: 
        use_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  artemis:
    user: artemis
    password: simetraehcapa
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: secretkey
hu:
  lacztam:
    token:
      keypaths:
        public: /tmp/k3p/public.pem
k3p:
  jwtTokenProperties:
    expireMinute: 600
    issuer: KeePassPlusPlus
    auth: auth
    algorithmSpecification: HMAC512
    algorithmSpecificationArgument: mysecret
logging:
  file:
    name: /tmp/k3p/log/keepass.log